# -*- coding: utf-8 -*-
"""mentalhealth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PVfOmwGOzFL9gWzIomO5lqBIciv0tNoj
"""

!pip install -q transformers datasets torch scikit-learn

import torch
import numpy as np
import pandas as pd
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split

df = pd.read_csv("/content/Combined Data.csv")   # <-- your file name
df = df[["statement", "status"]]
df.dropna(inplace=True)

label_map = {
    "Normal": 0,
    "Anxiety": 1,
    "Depression": 2,
    "Stress": 3
}

df["label"] = df["status"].map(label_map)
df.dropna(subset=['label'], inplace=True) # Remove rows where label is NaN
df["label"] = df["label"].astype(int) # Convert labels to integer type

label_map = {
    "Normal": 0,
    "Anxiety": 1,
    "Depression": 2,
    "Stress": 3
}

df["label"] = df["status"].map(label_map)
df.dropna(subset=['label'], inplace=True) # Remove rows where label is NaN
df["label"] = df["label"].astype(int) # Convert labels to integer type

df["label"].value_counts()

train_texts, val_texts, train_labels, val_labels = train_test_split(
    df["statement"].tolist(),
    df["label"].tolist(),
    test_size=0.1,        # 10% validation
    random_state=42,
    stratify=df["label"]
)

tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

train_enc = tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=128
)

val_enc = tokenizer(
    val_texts,
    truncation=True,
    padding=True,
    max_length=128
)

class MentalDataset(Dataset):
    def __init__(self, encodings, labels):
        self.enc = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.enc.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_ds = MentalDataset(train_enc, train_labels)
val_ds = MentalDataset(val_enc, val_labels)

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=4
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

from torch.optim import AdamW

train_loader = DataLoader(
    train_ds,
    batch_size=16,     # optimized
    shuffle=True
)

optimizer = AdamW(model.parameters(), lr=2e-5)

model.train()

for epoch in range(1):   # 👈 2 epochs is ENOUGH
    print(f"Epoch {epoch+1}")
    total_loss = 0

    for batch in train_loader:
        optimizer.zero_grad()

        batch = {k: v.to(device) for k, v in batch.items()}
        outputs = model(**batch)

        loss = outputs.loss
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print("Avg Loss:", total_loss / len(train_loader))

def predict_text_risk(text):
    model.eval()
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

    probs = torch.softmax(outputs.logits, dim=1)[0]

    risk = (
        probs[0]*10 +   # Normal
        probs[1]*40 +   # Anxiety
        probs[2]*80 +   # Depression
        probs[3]*60    # Stress
    )

    return int(risk.item())

predict_text_risk("I feel empty, hopeless, and tired of everything")

model.save_pretrained("mental_text_model")
tokenizer.save_pretrained("mental_text_model")

!zip -r mental_text_model.zip mental_text_model

from google.colab import files
files.download("mental_text_model.zip")