import React, { useState } from 'react'
import AppNav from './AppNav'
import './ChatPage.css'

const initialMessages = [
  { id: '1', author: 'assistant', text: 'Hello! I’m here to listen. Share anything on your mind and I’ll support you.' }
]

export default function ChatPage({ user, onLogout }) {
  const [messages, setMessages] = useState(initialMessages)
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)

  async function sendMessage() {
    if (!input.trim() || loading) return
    const userMessage = {
      id: Date.now().toString(),
      author: 'user',
      text: input.trim()
    }
    setMessages(prev => [...prev, userMessage])
    setInput('')
    setLoading(true)

    try {
      const response = await fetch('http://localhost:5000/api/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ message: userMessage.text }),
      })
      const data = await response.json()
      if (response.ok) {
        const assistantMessage = {
          id: `${Date.now()}-r`,
          author: 'assistant',
          text: data.reply
        }
        setMessages(prev => [...prev, assistantMessage])
      } else {
        console.error('Error:', data.error)
        const errorMessage = {
          id: `${Date.now()}-e`,
          author: 'assistant',
          text: 'Sorry, I couldn\'t process that. Please try again.'
        }
        setMessages(prev => [...prev, errorMessage])
      }
    } catch (err) {
      console.error('Fetch error:', err)
      const errorMessage = {
        id: `${Date.now()}-e`,
        author: 'assistant',
        text: 'Sorry, there was an error connecting to the server.'
      }
      setMessages(prev => [...prev, errorMessage])
    } finally {
      setLoading(false)
    }
  }

  function handleKeyDown(event) {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault()
      sendMessage()
    }
  }

  return (
    <div className="chat-page">
      <AppNav user={user} onLogout={onLogout} />
      <header className="chat-hero">
        <div>
          <span className="small-label">Chat Support</span>
          <h1>Talk through your thoughts in a calm, friendly space.</h1>
          <p>Use this space to reflect, share, and get gentle autogenerated responses.</p>
        </div>
      </header>

      <section className="chat-panel">
        <div className="chat-window">
          {messages.map((message) => (
            <div key={message.id} className={`chat-message ${message.author}`}>
              <div className="chat-author">{message.author === 'assistant' ? 'MindGuard' : user.name.split(' ')[0]}</div>
              <p>{message.text}</p>
            </div>
          ))}
        </div>

        <div className="chat-input-row">
          <textarea
            rows="3"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Type a thought, concern, or question..."
            disabled={loading}
          />
          <button onClick={sendMessage} className="send-button" disabled={loading}>
            {loading ? 'Sending...' : 'Send'}
          </button>
        </div>
      </section>
    </div>
  )
}
